const Bloodchemistry = [
  {
    typeid: 'fbs1',
    enname: 'FBS',
    thname: 'น้ำตาลในเลือด',
    sex: 'Both',
    min: 69.9,
    max: 125,
    result: { min: 'DIABA70', max: 'DIAB' },
    unit: 'mg/dL',
  },
  {
    typeid: 'bgc',
    enname: 'Blood Glucose',
    thname: 'น้ำตาลในเลือด',
    sex: 'Both',
    min: 69.9,
    max: 125,
    result: { min: 'DIABA70', max: 'DIAB' },
    unit: 'mg/dL',
  },
  {
    typeid: 'ldl1',
    enname: 'LDL',
    thname: 'ไขมันไม่ดี',
    sex: 'Both',
    min: 0,
    max: 129.2,
    result: { max: 'DYSLIPID' },
    unit: 'mg/dL',
  },
  {
    typeid: 'hdl1',
    enname: 'HDL',
    thname: 'ไขมันดี',
    sex: 'Male',
    min: 39.9,
    max: 1001.1,
    unit: 'mg/dL',
  },
  {
    typeid: 'hdl2',
    enname: 'HDL',
    thname: 'ไขมันดี',
    sex: 'Female',
    min: 49.9,
    max: 1001.1,
    unit: 'mg/dL',
  },
  {
    typeid: 'tgl1',
    enname: 'Triglyceride',
    thname: 'ไขมันไตรกลีเซอไรด์',
    sex: 'Both',
    min: 0,
    max: 149.2,
    result: { min: 'HIGHTG', max: 'HIGHTG' },
    unit: 'mg/dL',
  },
  {
    typeid: 'sgpt',
    enname: 'SGPT',
    thname: 'เอนไซม์ตับตัวที่ 1',
    sex: 'Male',
    min: 0,
    max: 41,
    result: { min: 'HIGHSGPT', max: 'HIGHSGPT' },
    unit: 'U/L',
  },
  {
    typeid: 'sgot',
    enname: 'SGOT',
    thname: 'เอนไซม์ตับตัวที่ 2',
    sex: 'Male',
    min: 0,
    max: 40,
    result: { min: 'HIGHSGOT', max: 'HIGHSGOT' },
    unit: 'U/L',
  },
  {
    typeid: 'cre1',
    enname: 'Creatinine',
    thname: 'ค่าการทำงานของไต',
    sex: 'Male',
    min: 0,
    max: 1.1702,
    result: { min: 'HIGHCRE', max: 'HIGHCRE' },
    unit: 'mg/dL',
  },
  {
    typeid: 'cre2',
    enname: 'Creatinine',
    thname: 'ค่าการทำงานของไต',
    sex: 'Female',
    min: 0,
    max: 0.9502,
    result: { min: 'HIGHCRE', max: 'HIGHCRE' },
    unit: 'mg/dL',
  },
  {
    typeid: 'hba1c1',
    enname: 'HbA1C',
    thname: 'ระดับน้ำตาลสะสม',
    sex: 'Both',
    min: 0,
    max: 5.700001,
    unit: '%',
  },
  {
    typeid: 'alp1',
    enname: 'ALP',
    thname: 'อัลคาไลน์ฟอสฟาเตส',
    sex: 'Male',
    min: 34.98,
    max: 130.2,
    unit: 'U/L',
  },
  {
    typeid: 'alp2',
    enname: 'ALP',
    thname: 'อัลคาไลน์ฟอสฟาเตส',
    sex: 'Female',
    min: 34.98,
    max: 105.2,
    unit: 'U/L',
  },
  {
    typeid: 'chol1',
    enname: 'Cholesterol',
    thname: 'ไขมันคลอเรสเตอรอล',
    sex: 'Both',
    min: 0,
    max: 199.2,
    result: { min: 'DYSLIPID', max: 'DYSLIPID' },
    unit: 'mg/dL',
  },
  {
    typeid: 'uric1',
    enname: 'Uric Acid',
    thname: 'กรดยูริก',
    sex: 'Male',
    min: 0,
    max: 7.00011,
    result: { max: 'HIGHURIC' },
    unit: 'mg/dL',
  },
  {
    typeid: 'uric2',
    enname: 'Uric Acid',
    thname: 'กรดยูริก',
    sex: 'Female',
    min: 0,
    max: 5.70011,
    result: { max: 'HIGHURIC' },
    unit: 'mg/dL',
  },
  {
    typeid: 'sgpt1',
    enname: 'SGPT',
    thname: 'เอนไซม์ตับตัวที่ 1',
    sex: 'Female',
    min: 0,
    max: 33.02,
    result: { min: 'HIGHSGPT', max: 'HIGHSGPT' },
    unit: 'U/L',
  },
  {
    typeid: 'sgot1',
    enname: 'SGOT',
    thname: 'เอนไซม์ตับตัวที่ 2',
    sex: 'Female',
    min: 0,
    max: 32.02,
    result: { min: 'HIGHSGOT', max: 'HIGHSGOT' },
    unit: 'U/L',
  },
  {
    typeid: 'bun',
    enname: 'BUN',
    thname: 'ค่าการทำงานของไต ',
    sex: 'Both',
    min: 0,
    max: 20.02,
    result: { max: 'HighBUN' },
    unit: 'mg/dl',
  },
  {
    typeid: 'tgfr',
    enname: 'Thai GFR',
    thname: 'ค่าการทำงานของไต ',
    sex: 'Both',
    unit: 'ml/min/1.73 m^2',
  },
  {
    typeid: 'topro',
    enname: 'Total Protein',
    thname: '',
    sex: 'Both',
    min: 0.659998,
    max: 8.70002,
    unit: 'g/dl',
  },
  {
    typeid: 'albu',
    enname: 'Albumin',
    thname: 'อัลบูมิน',
    sex: 'Both',
    min: 3.49998,
    max: 5.200002,
    result: { min: 'LOWALBUMIN', max: '' },
    unit: 'g/dl',
  },
  {
    typeid: 'globu',
    enname: 'Globulin',
    thname: '',
    sex: 'Both',
    min: 2.19998,
    max: 4.200002,
    unit: 'g/dl',
  },
  { typeid: 'agra', enname: 'A/G Ratio', thname: '', sex: 'Both', min: 0.99998, max: 2.0002 },
  {
    typeid: 'tobil',
    enname: 'Total Bilirubin',
    thname: '',
    sex: 'Both',
    min: 0,
    max: 1.2002,
    result: { min: 'HIGHTOTAL_BILIRUBIN', max: '' },
    unit: 'mg/dl',
  },
  {
    typeid: 'dobil',
    enname: 'Direct Bilirubin',
    thname: '',
    sex: 'Both',
    min: 0,
    max: 0.29002,
    result: { min: 'HIGHDIRECT_BILIRUBIN', max: 'HIGHDIRECT_BILIRUBIN' },
    unit: 'mg/dl',
  },
  {
    typeid: 'ggt',
    enname: 'GGT',
    thname: 'เอนไซม์ตับตัวที่3',
    sex: 'Both',
    min: 5.98,
    max: 42.02,
    result: { min: 'HIGHGGT', max: 'HIGHGGT' },
    unit: 'U/L',
  },
  {
    typeid: 'amyl',
    enname: 'Amylase',
    thname: 'เอนไซม์อะไมเลส',
    sex: 'Both',
    min: 12.99998,
    max: 523.0002,
    result: { min: 'HIGHAMYLASE', max: 'HIGHAMYLASE' },
    unit: 'U/L',
  },
  {
    typeid: 'sodium',
    enname: 'Sodium',
    thname: 'โซเดียม',
    sex: 'Both',
    min: 135.98,
    max: 145.02,
    result: { min: 'LOWSODIUM', max: 'HIGHSODIUM' },
    unit: 'mmol/L',
  },
  {
    typeid: 'potas',
    enname: 'Potassium',
    thname: 'โพแทสเซียม',
    sex: 'Both',
    min: 3.49998,
    max: 5.1002,
    result: { min: 'LOWPOTASSIUM', max: 'HIGHPOTASSIUM' },
    unit: 'mmol/L',
  },
  {
    typeid: 'chlor1',
    enname: 'Chloride',
    thname: 'คลอไรด์',
    sex: 'Both',
    min: 97.98,
    max: 107.002,
    result: { min: 'LOWCHLORIDE', max: 'HIGHCHLORIDE' },
    unit: 'mmol/L',
  },
  {
    typeid: 'bicar',
    enname: 'Bicarbonate',
    thname: 'ไบคาร์บอเนต',
    sex: 'Both',
    min: 21.9998,
    max: 30.00002,
    result: { min: 'LOWBICARB', max: 'HIGHBICARB' },
    unit: 'mmol/L',
  },
  {
    typeid: 'cal',
    enname: 'Calcium',
    thname: 'แคลเซียม',
    sex: 'Both',
    min: 8.5998,
    max: 10.0002,
    result: { min: 'LOWCALCIUM', max: 'HIGHCALCIUM' },
    unit: 'mg/dl',
  },
  {
    typeid: 'phos',
    enname: 'Phosphorus',
    thname: 'ฟอสฟอรัส',
    sex: 'Both',
    min: 2.4998,
    max: 4.50002,
    result: { min: 'LOWPHOS', max: 'HIGHPHOS' },
    unit: 'mg/dl',
  },
];

const Bodyscan = [
  {
    typeid: 'muscle1',
    enname: 'Muscle Mass',
    thname: 'มวลกล้ามเนื้อ(ชาย)',
    sex: 'Male',
    min: 11.1,
    result: { min: 'LOWMM', max: '' },
  },
  {
    typeid: 'muscle2',
    enname: 'Muscle Mass',
    thname: 'มวลกล้ามเนื้อ(หญิง)',
    sex: 'Female',
    min: 8.1,
    result: { min: 'LOWMM', max: '' },
  },
  {
    typeid: 'fat1',
    enname: 'Fat Mass',
    thname: 'มวลไขมัน (ชาย)',
    sex: 'Male',
    min: 10.4998,
    max: 13.900002,
    result: { min: '', max: 'HIGH' },
    unit: 'kg',
  },
  {
    typeid: 'fat2',
    enname: 'Fat Mass',
    thname: 'มวลไขมัน (หญิง)',
    sex: 'Female',
    min: 11.6998,
    max: 17.60002,
    result: { min: '', max: 'HIGH' },
    unit: 'kg',
  },
  {
    typeid: 'perfat1',
    enname: 'Percent Fat',
    thname: 'เปอร์เซ็นต์ไขมัน(ชาย)',
    sex: 'Male',
    min: 14.9998,
    max: 20.00002,
    result: { min: '', max: 'HIGHPERCENTFAT' },
    unit: '%',
  },
  {
    typeid: 'perfat2',
    enname: 'Percent Fat',
    thname: 'เปอร์เซ็นต์ไขมัน (หญิง)',
    sex: 'Female',
    min: 19.9998,
    max: 30.00002,
    result: { min: '', max: 'HIGHPERCENTFAT' },
    unit: '%',
  },
  {
    typeid: 'vifa1',
    enname: 'Visceral Fat Area',
    thname: 'พื้นที่ไขมันในช่องท้อง(ชาย)',
    sex: 'Male',
    min: 0,
    max: 100.0002,
    result: { max: 'HIGHVISCERA' },
  },
  {
    typeid: 'vifa2',
    enname: 'Visceral fat area',
    thname: 'พื้นที่ไขมันในช่องท้อง(หญิง)',
    sex: 'Female',
    min: 0,
    max: 80.0002,
    result: { max: 'HIGHVISCERA' },
  },
];

const Eyesexamination = [
  { typeid: 'vwgr1', enname: 'Vision with glasses (R)', thname: 'สายตาขวา (ใส่แว่น)', sex: 'Both' },
  {
    typeid: 'vwgl1',
    enname: 'Vision with glasses (L)',
    thname: 'สายตาซ้าย (ใส่แว่น)',
    sex: 'Both',
  },
  {
    typeid: 'vwogr1',
    enname: 'Vision without glasses (R)',
    thname: 'สายตาขวา (ไม่ใส่แว่น)',
    sex: 'Both',
  },
  {
    typeid: 'vwogl1',
    enname: 'Vision without glasses (L)',
    thname: 'สายตาซ้าย (ไม่ใส่แว่น)',
    sex: 'Both',
  },
  { typeid: 'colb1', enname: 'Color Blindness', thname: '', sex: 'Both' },
  { typeid: 'tonor1', enname: 'Tonometry (R)', thname: '', sex: 'Both' },
  { typeid: 'tonol1', enname: 'Tonometry (L)', thname: '', sex: 'Both' },
  { typeid: 'eyedeta', enname: 'Detail', thname: '', sex: 'Both' },
  { typeid: 'eyefile1', enname: 'Eye Image', thname: '', sex: 'Both' },
];

const Freeradicalandantioxidant = [
  {
    typeid: 'frto',
    enname: 'Free Radical total',
    thname: 'ปริมาณสารอนุมูลอิสระ',
    sex: 'Both',
    min: 0,
    max: 300.0002,
    result: { min: 'HIGHFREERADICAL ', max: 'HIGHFREERADICAL ' },
  },
  {
    typeid: 'plas',
    enname: 'Plasma antioxidant test ',
    thname: 'ปริมาณสารต้านอนุมูลอิสระ',
    sex: 'Both',
    min: 2200,
    result: { min: 'LOWPLASMA ANTIOXIDANT', max: '' },
  },
  {
    typeid: 'mina',
    enname: 'Vitamin A',
    thname: 'วิตามินเอ',
    sex: 'Both',
    min: 0.799998,
    max: 2.900002,
    result: { min: 'LOWVITAMINA', max: 'HIGHVITAMINA' },
    unit: 'umol/L',
  },
  {
    typeid: 'alpha',
    enname: 'Alpha-Carotene',
    thname: 'อัลฟ่าแคโรทีน',
    sex: 'Both',
    min: 0,
    max: 0.32,
    result: { min: 'LOWALPHA', max: 'HIGHALPHA' },
    unit: 'umol/L',
  },
  {
    typeid: 'beta',
    enname: 'Beta-Carotene',
    thname: 'เบต้าแคโรทีน',
    sex: 'Both',
    min: 0.099999,
    max: 1.100002,
    result: { min: 'LOWBETA', max: 'HIGHBETA' },
    unit: 'umol/L',
  },
  {
    typeid: 'lyco',
    enname: 'Lycopene',
    thname: 'ไลโคปีน',
    sex: 'Both',
    min: 0.09998,
    max: 1.30002,
    result: { min: 'LOWLYCOPENE', max: 'HIGHLYCOPENE' },
    unit: 'umol/L',
  },
  {
    typeid: 'vitc',
    enname: 'Vitamin C ',
    thname: 'วิตามินซี',
    sex: 'Both',
    min: 11.39998,
    max: 79.50002,
    result: { min: 'LOWVITC', max: 'HIGHVITC' },
    unit: 'umol/L',
  },
  {
    typeid: 'gamma',
    enname: 'Gamma-Tocopherol',
    thname: 'วิตามินอีชนิดแกมม่า',
    sex: 'Both',
    min: 0.49998,
    max: 6.20002,
    result: { min: 'LOWGAMMA', max: 'HIGHGAMMA' },
    unit: 'umol/L',
  },
  {
    typeid: 'alpha1',
    enname: 'Alpha-Tocopherol',
    thname: 'วิตามินอีชนิดแอลฟ่า',
    sex: 'Both',
    min: 7.98,
    max: 42.02,
    result: { min: 'LOWALPHA', max: 'HIGHALPHA' },
    unit: 'umol/L',
  },
  {
    typeid: 'coe',
    enname: 'Coenzyme Q10',
    thname: 'โคเอนไซม์คิวเทน',
    sex: 'Both',
    min: 0.49999,
    max: 1.90002,
    result: { min: 'LOWCOENZYME', max: 'HIGHCOENZYME' },
    unit: 'umol/L',
  },
  {
    typeid: 'vitd',
    enname: 'Total 25-OH Vitamin D',
    thname: 'วิตามินดี',
    sex: 'Both',
    min: 29.99998,
    max: 99.00002,
    result: { min: 'LOWVITAMIND', max: '' },
    unit: 'ug/L',
  },
  {
    typeid: 'vitb12',
    enname: 'Vitamin B12',
    thname: 'วิตามินบี12',
    sex: 'Both',
    min: 196.99998,
    max: 771.0002,
    result: { min: 'LOWVITB12', max: 'HIGHVIVB12' },
    unit: 'pg/ml',
  },
];

const Hematology = [
  {
    typeid: 'hmg1',
    enname: 'Hemoglobin',
    thname: 'ความเข้มข้นเลือด',
    sex: 'Male',
    min: 12.98,
    max: 17.42,
    result: { min: 'ANEMIA,HIGHBLOOD', max: 'ANEMIA,HIGHBLOOD' },
    unit: 'g/dL',
  },
  {
    typeid: 'hmg2',
    enname: 'Hemoglobin',
    thname: 'ความเข้มข้นเลือด',
    sex: 'Female',
    min: 11.98,
    max: 16.02,
    result: { min: 'ANEMIA,HIGHBLOOD', max: 'ANEMIA,HIGHBLOOD' },
    unit: 'g/dL',
  },
  {
    typeid: 'wbc1',
    enname: 'White Blood Cell',
    thname: 'เม็ดเลือดขาว',
    sex: 'Both',
    min: 3999.9,
    max: 11000.2,
    result: { min: 'LOWWHITE', max: 'HIGHWHITE' },
    unit: '/mm3',
  },
  {
    typeid: 'ptl1',
    enname: 'Platelet',
    thname: 'เกร็ดเลือด',
    sex: 'Both',
    min: 149999.9,
    max: 400000.2,
    result: { min: 'LOWPLATE', max: 'HIGHPLATE' },
    unit: '/mm3',
  },
  {
    typeid: 'hct1',
    enname: 'HCT',
    thname: 'ความเข้มข้นเลือด',
    sex: 'Male',
    min: 39.9,
    max: 54.2,
    result: { min: 'ANEMIA,HIGHBLOOD', max: 'ANEMIA,HIGHBLOOD' },
    unit: '%',
  },
  {
    typeid: 'hct2',
    enname: 'HCT',
    thname: 'ความเข้มข้นเลือด',
    sex: 'Female',
    min: 36.9,
    max: 47.11,
    result: { min: 'ANEMIA,HIGHBLOOD', max: 'ANEMIA,HIGHBLOOD' },
    unit: '%',
  },
  {
    typeid: 'mcv',
    enname: 'MCV',
    thname: 'ลักษณะเม็ดเลือดแดง',
    sex: 'Both',
    min: 79.99998,
    max: 97.800002,
    unit: 'fL',
  },
  {
    typeid: 'mch',
    enname: 'MCH',
    thname: 'ลักษณะเม็ดเลือดแดง',
    sex: 'Both',
    min: 25.199998,
    max: 32.002,
    unit: 'pg',
  },
  {
    typeid: 'mchc',
    enname: 'MCHC',
    thname: 'ลักษณะเม็ดเลือดแดง',
    sex: 'Both',
    min: 30.98,
    max: 35.02,
    unit: 'g/dL',
  },
  {
    typeid: 'neut',
    enname: 'Neutrophil',
    thname: 'ชนิดของเม็ดเลือดขาว',
    sex: 'Both',
    min: 43.69998,
    max: 70.0002,
    unit: '%',
  },
  {
    typeid: 'lyml',
    enname: 'Lymphocyte',
    thname: 'ชนิดของเม็ดเลือดขาว',
    sex: 'Both',
    min: 19.99999,
    max: 44.50002,
    unit: '%',
  },
  {
    typeid: 'eosi',
    enname: 'Eosinophil',
    thname: 'ชนิดของเม็ดเลือดขาว',
    sex: 'Both',
    min: 0.69998,
    max: 9.20002,
    unit: '%',
  },
  {
    typeid: 'mono',
    enname: 'Monocyte',
    thname: 'ชนิดของเม็ดเลือดขาว',
    sex: 'Both',
    min: 3.39998,
    max: 9.80002,
    unit: '%',
  },
  {
    typeid: 'basl',
    enname: 'Basophil',
    thname: 'ชนิดของเม็ดเลือดขาว',
    sex: 'Both',
    min: 0,
    max: 1.0002,
    unit: '%',
  },
  {
    typeid: 'esr',
    enname: 'ESR',
    thname: 'ตัววัดการอักเสบของร่างกาย',
    sex: 'Both',
    min: 0,
    max: 19.02,
    unit: 'mm/hr',
  },
  {
    typeid: 'bfm',
    enname: 'Blood Film for Malaria',
    thname: 'ตรวจการติดเชื้อมาลาเรีย',
    sex: 'Both',
    min: 0,
    result: { min: 'NOT FOUND', max: 'FOUND' },
  },
  { typeid: 'hbty', enname: 'Hb Typing', thname: '', sex: 'Both' },
  { typeid: 'hbtya', enname: 'Hb Type A', thname: '', sex: 'Both' },
  { typeid: 'hbtya2', enname: 'Hb TypeA2', thname: '', sex: 'Both' },
  { typeid: 'hbtyf', enname: 'Hb Type F', thname: '', sex: 'Both' },
  { typeid: 'hbtye', enname: 'Hb TypeE', thname: '', sex: 'Both' },
  { typeid: 'osmo', enname: 'Osmotic Fragility', thname: '', sex: 'Both' },
  { typeid: 'abogr', enname: 'ABO Group', thname: 'กรุ๊ปเลือด', sex: 'Both' },
  { typeid: 'rhg', enname: 'Rh Group', thname: 'หมู่เลือด Rh', sex: 'Both' },
];

const Hormone = [
  {
    typeid: 'dhea1',
    enname: 'DHEA-sulphate',
    thname: 'ต้นกำเนิดฮอร์โมนเพศ(ชาย)',
    sex: 'Male',
    unit: 'ug/dL',
  },
  {
    typeid: 'dhea2',
    enname: 'DHEA-sulphate',
    thname: 'ต้นกำเนิดฮอร์โมนเพศ(หญิง)',
    sex: 'Female',
    unit: 'ug/dL',
  },
  {
    typeid: 'testo',
    enname: 'Testosterone',
    thname: 'ฮอร์โมนเทสโทสเตอโรน',
    sex: 'Both',
    unit: 'ng/dL',
  },
  {
    typeid: 'proges',
    enname: 'Progesterone',
    thname: 'ฮอร์โมนโปเจสเตอโรน',
    sex: 'Both',
    unit: 'ng/ml',
  },
  { typeid: 'estra', enname: 'Estradiol', thname: 'ฮอร์โมนEstradiol', sex: 'Both', unit: 'pg/ml' },
  { typeid: 'cor', enname: 'Cortisol', thname: 'คอร์ติซอล', sex: 'Both', unit: 'ug/dL' },
  { typeid: 'insu', enname: 'Insulin', thname: 'อินซูลิน', sex: 'Both', unit: 'uU/ml' },
  { typeid: 'igf1', enname: 'IGF1', thname: '', sex: 'Both', unit: 'ng/ml' },
];

const Immunology = [
  {
    typeid: 'psa1',
    enname: 'PSA',
    thname: 'สารคัดกรองมะเร็งต่อมลูกหมาก',
    sex: 'Male',
    min: 0,
    max: 4.0000002,
  },
  {
    typeid: 'hbsag',
    enname: 'HBsAg',
    thname: 'ตรวจการติดเชื้อและภูมิคุ้มกันไวรัสตับอักเสบบี',
    sex: 'Both',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
  {
    typeid: 'ahbs',
    enname: 'Anti HBs',
    thname: 'ตรวจการติดเชื้อและภูมิคุ้มกันไวรัสตับอักเสบบี',
    sex: 'Both',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
  {
    typeid: 'ahbc',
    enname: 'Anti HBc',
    thname: 'ตรวจการติดเชื้อและภูมิคุ้มกันไวรัสตับอักเสบบี',
    sex: 'Both',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
  {
    typeid: 'ahi',
    enname: 'Anti HAV IgG',
    thname: 'ตรวจภูมิคุมกันไวรัสตับอักเสบเอ',
    sex: 'Both',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
  {
    typeid: 'ahcv',
    enname: 'Anti HCV',
    thname: 'ตรวจการติดเชื้อไวรัสตับอักเสบซี',
    sex: 'Both',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
  {
    typeid: 'rigg',
    enname: 'Rubella IgG',
    thname: 'ตรวจภูมิคุ้มกันหัดเยอรมัน',
    sex: 'Both',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
  {
    typeid: 'tpha',
    enname: 'TPHA',
    thname: 'ตรวจการติดเชื้อซิฟิลิส',
    sex: 'Both',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
  { typeid: 't3', enname: 'T3', thname: 'ตรวจการทำงานของต่อมไทรอยด์', sex: 'Both' },
  { typeid: 't4', enname: 'T4', thname: 'ตรวจการทำงานของต่อมไทรอยด์', sex: 'Both' },
  { typeid: 'ft4', enname: 'Free T4', thname: 'ตรวจการทำงานของต่อมไทรอยด์', sex: 'Both' },
  {
    typeid: 'afp',
    enname: 'AFP',
    thname: 'สารคัดกรองมะเร็งตับ',
    sex: 'Both',
    min: 0,
    max: 7.0002,
    result: { min: 'HIGHAFP', max: 'HIGHAFP' },
    unit: 'ng/ml',
  },
  {
    typeid: 'ceanon',
    enname: 'CEA (Non-Smoke)',
    thname: 'สารคัดกรองมะเร็งลำไส้',
    sex: 'Both',
    min: 0,
    max: 3.80002,
    result: { min: 'HIGHCEA(NON)', max: 'HIGHCEA(NON)' },
    unit: 'ng/ml',
  },
  {
    typeid: 'cea',
    enname: 'CEA (Smoke)',
    thname: 'สารคัดกรองมะเร็งลำไส้',
    sex: 'Both',
    min: 0,
    max: 5.50002,
    result: { min: 'HIGHCEA(SMOKE)', max: 'HIGHCEA(SMOKE)' },
    unit: 'ng/ml',
  },
  { typeid: 'ft3', enname: 'Free T3', thname: 'ตรวจการทำงานของต่อมไทรอยด์', sex: 'Both' },
  {
    typeid: 'fta',
    enname: 'FTA-ABS',
    thname: 'ตรวจการติดเชื้อซิฟิลิส',
    sex: 'Both',
    result: { min: 'NONREACTIVE', max: 'REACTIVE' },
  },
  {
    typeid: 'vdrl',
    enname: 'VDRL',
    thname: 'ตรวจการติดเชื้อซิฟิลิส',
    sex: 'Both',
    result: { min: 'NONREACTIVE', max: 'REACTIVE' },
  },
  { typeid: 'tsh', enname: 'TSH', thname: 'ตรวจการทำงานของต่อมไทรอยด์', sex: 'Both' },
  {
    typeid: 'ca125',
    enname: 'CA 125',
    thname: 'สารคัดกรองมะเร็งรังไข่',
    sex: 'Female',
    min: 0,
    max: 35.02,
    unit: 'U/ml',
  },
  {
    typeid: 'ahigm',
    enname: 'Anti HAV IgM',
    thname: '',
    sex: 'Both',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
];

const Inflammation = [
  {
    typeid: 'homo',
    enname: 'Homocysteine',
    thname: '',
    sex: 'Both',
    min: 0,
    max: 15.0002,
    result: { min: '', max: 'HIGHHOMOCYSTEINE' },
    unit: 'umol/L',
  },
  {
    typeid: 'creac',
    enname: 'C-reactive protein (high sense)',
    thname: '',
    sex: 'Both',
    unit: 'mg/L',
  },
];

const Micronutrient = [
  {
    typeid: 'ferr',
    enname: 'Ferritin',
    thname: '',
    sex: 'Both',
    min: 12.99998,
    max: 150.0002,
    unit: 'ng/ml',
  },
  {
    typeid: 'fola',
    enname: 'Folate',
    thname: 'โฟเลท',
    sex: 'Both',
    min: 3.89998,
    max: 26.80002,
    result: { min: 'LOWFOLATE', max: 'HIGHFOLATE' },
    unit: 'ng/ml',
  },
  {
    typeid: 'chrom',
    enname: 'Chromium',
    thname: 'โครเมี่ยม',
    sex: 'Both',
    min: 0,
    max: 5.00002,
    result: { min: '', max: 'HIGHCHROMIUM' },
    unit: 'ug/L',
  },
  {
    typeid: 'zinc',
    enname: 'Zinc',
    thname: 'สังกะสี',
    sex: 'Both',
    min: 54.9998,
    max: 92.500002,
    result: { min: 'LOWZINC', max: 'HIGHZINC' },
    unit: 'ug/dL',
  },
  {
    typeid: 'cop',
    enname: 'copper',
    thname: 'ทองแดง',
    sex: 'Both',
    min: 79.39998,
    max: 202.3002,
    result: { min: 'LOWCOPPER', max: 'HIGHCOPPER' },
    unit: 'ug/dL',
  },
  {
    typeid: 'sele',
    enname: 'Selenium',
    thname: 'ซีลีเนียม',
    sex: 'Both',
    min: 78.999998,
    max: 141.00002,
    result: { min: 'LOWSELENIUM', max: 'HIGHSELENIUM' },
    unit: 'ug/L',
  },
];

const Othertest = [
  { typeid: 'ugi1', enname: 'UGI', thname: '', sex: 'Both' },
  { typeid: 'gastos1', enname: 'Gastoscope', thname: '', sex: 'Both' },
  { typeid: 'basxray', enname: 'Barium Enema X-ray', thname: '', sex: 'Both' },
  { typeid: 'colos1x', enname: 'Colonoscop', thname: '', sex: 'Both' },
  { typeid: 'bonlu1', enname: 'Bone density Lumbar & Hips', thname: '', sex: 'Both' },
];

const Physicalexamination = [
  {
    typeid: 'sbp1',
    enname: 'Systolic BP',
    thname: 'ความดันโลหิตตัวบน',
    sex: 'Both',
    min: 89.98,
    max: 139.02,
    result: { min: 'HTA90', max: 'HT' },
    unit: 'mmHg',
  },
  {
    typeid: 'dbp1',
    enname: 'Diastolic BP',
    thname: 'ความดันโลหิตตัวล่าง',
    sex: 'Both',
    min: 59.98,
    max: 89.02,
    result: { min: 'HTA60', max: 'HT' },
    unit: 'mmHg',
  },
  {
    typeid: 'bmi1',
    enname: 'BMI',
    thname: 'ดัชนีมวลกาย',
    sex: 'Both',
    min: 18.49999998,
    max: 22.999999999,
    result: { min: 'LOWEIGHT', max: 'LOWEIGHT' },
  },
  {
    typeid: 'hr1',
    enname: 'Pulse Rate',
    thname: 'ชีพจร',
    sex: 'Both',
    min: 59.9,
    max: 100.11,
    result: { min: 'LPA60', max: 'HPA100' },
    unit: 'bpm',
  },
  {
    typeid: 'hei1',
    enname: 'Height',
    thname: 'ส่วนสูง',
    sex: 'Both',
    result: { min: '', max: '' },
    unit: 'cm',
  },
  {
    typeid: 'wei1',
    enname: 'Weight',
    thname: 'น้ำหนัก',
    sex: 'Both',
    result: { min: '', max: '' },
    unit: 'kg',
  },
  {
    typeid: 'wrcis1',
    enname: 'Waist Circumference',
    thname: 'รอบเอว',
    sex: 'Male',
    min: 0,
    max: 90.002,
    result: { max: 'HIGHWAIST' },
    unit: 'cm',
  },
  {
    typeid: 'waci',
    enname: 'Waist Circumference',
    thname: 'รอบเอว',
    sex: 'Female',
    min: 0,
    max: 80.002,
    result: { max: 'HIGHWAIST' },
    unit: 'cm',
  },
];

const Stoolanalysis = [
  { typeid: 'stool', enname: 'Stool Color', thname: '', sex: 'Both' },
  { typeid: 'wbc', enname: 'WBC in stool', thname: '', sex: 'Both' },
  { typeid: 'rbc', enname: 'RBC in stool ', thname: '', sex: 'Both' },
  { typeid: 'ovpa', enname: 'Ova & Parasite', thname: '', sex: 'Both' },
  { typeid: 'fung', enname: 'Fungus', thname: '', sex: 'Both' },
  {
    typeid: 'occu',
    enname: 'Occult blood',
    thname: 'เลือดปนในอุจจาระ',
    sex: 'Both',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
  { typeid: 'gross', enname: 'Gross blood', thname: '', sex: 'Both' },
  { typeid: 'stocs', enname: 'Stool C/S', thname: '', sex: 'Both' },
];

const Thinprep = [
  { typeid: 'thin1', enname: 'ThinPrep', thname: 'ThinPrep', sex: 'Both' },
  { typeid: 'paps1', enname: 'Pap Smear', thname: 'Pap Smear', sex: 'Both' },
];

const Toxicology = [
  {
    typeid: 'leadnor',
    enname: 'Lead (Normal)',
    thname: 'ปริมาณตะกั่วในเลือดในคนปกติ',
    sex: 'Both',
    min: 0,
    max: 29.00002,
    unit: 'ug/dl',
  },
  {
    typeid: 'leadex',
    enname: 'Lead (Expose)',
    thname: 'ปริมาณตะกั่วในเลือดในคนที่สัมผัสตะกั่ว',
    sex: 'Both',
    min: 0,
    max: 59.00002,
    unit: 'ug/dl',
  },
  {
    typeid: 'merc',
    enname: 'Mercury',
    thname: 'ปริมาณปรอทในเลือด',
    sex: 'Both',
    min: 0,
    max: 1.0002,
    unit: 'ug/dl',
  },
  {
    typeid: 'amph',
    enname: 'Amphetamine',
    thname: 'ตรวจสารแอมเฟตามีนในปัสสาวะ',
    sex: 'Both',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
  {
    typeid: 'morphine',
    enname: 'Morphine',
    thname: '',
    sex: 'Both',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
  {
    typeid: 'cannabino',
    enname: 'Cannabinoids',
    thname: '',
    sex: 'Both',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
  {
    typeid: 'cocaine',
    enname: 'Cocaine',
    thname: '',
    sex: 'Both',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
  {
    typeid: 'benzodia',
    enname: 'Benzodiazepines',
    thname: '',
    sex: 'Both',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
];

const Urineexamination = [
  {
    typeid: 'rbcur1',
    enname: 'RBC in Urine',
    thname: 'เม็ดเลือดแดงในปัสสาวะ',
    sex: 'Both',
    min: 0,
    max: 2.02,
    result: { max: 'HIGHRBCUR' },
    unit: 'Cells/HPF',
  },
  {
    typeid: 'wbcur1',
    enname: 'WBC in Urine',
    thname: 'เม็ดเลือดขาวในปัสสาวะ',
    sex: 'Both',
    min: 0,
    max: 10.02,
    result: { max: 'HIGHWBCUR' },
    unit: 'Cells/HPF',
  },
  {
    typeid: 'protur1',
    enname: 'Protein in Urine',
    thname: 'โปรตีนในปัสสาวะ',
    sex: 'Both',
    min: 0,
    max: 1.01,
    result: { max: 'HIGHPROUR' },
  },
  { typeid: 'urine', enname: 'Urine Color', thname: '', sex: 'Both' },
  { typeid: 'spgr', enname: 'Sp.gr', thname: '', sex: 'Both' },
  { typeid: 'ph', enname: 'pH', thname: '', sex: 'Both' },
  { typeid: 'gliu', enname: 'Glucose in urine', thname: 'ปริมาณน้ำตาลในปัสสาวะ', sex: 'Both' },
  { typeid: 'urob', enname: 'Urobilinogen', thname: '', sex: 'Both' },
  { typeid: 'keto', enname: 'Ketone', thname: '', sex: 'Both' },
  {
    typeid: 'urptes',
    enname: 'Urine Pregnancy Test ',
    thname: 'ตรวจการตั้งครรภ์',
    sex: 'Female',
    result: { min: 'NEGATIVE', max: 'POSITIVE' },
  },
  { typeid: 'bili', enname: 'Bilirubin', thname: '', sex: 'Both' },
  { typeid: 'erythro', enname: 'Erythrocytes', thname: '', sex: 'Both' },
  { typeid: 'microsco', enname: 'Microscopic Exam', thname: '', sex: 'Both' },
];

const Xray = [
  { typeid: 'lsxray', enname: 'L-S Spine', thname: '', sex: 'Both' },
  { typeid: 'chestx', enname: 'Chest X-Rays', thname: '', sex: 'Both' },
  { typeid: 'generalx', enname: 'General X-ray', thname: '', sex: 'Both' },
  { typeid: 'utrlb', enname: 'Ultrasound Breast', thname: '', sex: 'Both' },
  { typeid: 'ctx', enname: 'CT', thname: '', sex: 'Male' },
  { typeid: 'mrix', enname: 'MRI', thname: '', sex: 'Male' },
  { typeid: 'usup1', enname: 'U / S (Upper)', thname: '', sex: 'Both' },
  { typeid: 'uslow1', enname: 'U / S (Lower)', thname: '', sex: 'Both' },
  { typeid: 'uswhol1', enname: 'U / S (Whole)', thname: '', sex: 'Both' },
  { typeid: 'mamog1', enname: 'Mammogram', thname: '', sex: 'Both' },
  { typeid: 'usgeneral', enname: 'General Ultrasound', thname: '', sex: 'Both' },
];

const HealthGroup = [
  { groupid: 'Bloodchemistry', name: 'Blood Chemistry', data: Bloodchemistry },
  { groupid: 'Bodyscan', name: 'Body Scan', data: Bodyscan },
  { groupid: 'Eyesexamination', name: 'Eyes Examination', data: Eyesexamination },
  {
    groupid: 'Freeradicalandantioxidant',
    name: 'Free Radical & Antioxidant',
    data: Freeradicalandantioxidant,
  },
  { groupid: 'Hematology', name: 'Hematology', data: Hematology },
  { groupid: 'Hormone', name: 'Hormone', data: Hormone },
  { groupid: 'Immunology', name: 'Immunology', data: Immunology },
  { groupid: 'Inflammation', name: 'Inflammation', data: Inflammation },
  { groupid: 'Micronutrient', name: 'Micronutrient', data: Micronutrient },
  { groupid: 'Physicalexamination', name: 'Physical Examination', data: Physicalexamination },
  { groupid: 'Stoolanalysis', name: 'Stool Analysis', data: Stoolanalysis },
  { groupid: 'Thinprep', name: 'Thin Prep', data: Thinprep },
  { groupid: 'Toxicology', name: 'Toxicology', data: Toxicology },
  { groupid: 'Urineexamination', name: 'Urine Examination', data: Urineexamination },
  { groupid: 'Xray', name: 'X-Ray', data: Xray },
  { groupid: 'Othertest', name: 'Other Test', data: Othertest },
];

export {
  HealthGroup,
  Bloodchemistry,
  Bodyscan,
  Eyesexamination,
  Freeradicalandantioxidant,
  Hematology,
  Hormone,
  Immunology,
  Inflammation,
  Micronutrient,
  Othertest,
  Physicalexamination,
  Stoolanalysis,
  Thinprep,
  Toxicology,
  Urineexamination,
  Xray,
};
